// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Abdur Razzak Sawon (https://sketchfab.com/md.abdur.razzak.sawon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cartoon-frog-wide-eyes-big-smile-3f98649474184f98a77c7e89a9d1da7c
Title: Cartoon frog, wide eyes, big smile.
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Person(props) {
  const { nodes, materials } = useGLTF(
    "/cartoon_frog_wide_eyes_big_smile..glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.place_holder}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/cartoon_frog_wide_eyes_big_smile..glb");
